# How to run -> docker-compose -f docker-compose.yml up
version: '3.9'

services:

  mailserver:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
